### ISSUE TITLE
Flexible editor display template not visible

### ISSUE THREAD

**Issue by jdjoshuadavison** [formfcw/directus-extension-flexible-editor#23]
**Describe the bug**
I am using the flexible editor field as the display template for one of my models. The flexible editor field is set to "flexible editor" for the display template, which says "display the content of Flexible Editor as plain text." In some places this is resulting in no value being visible. For example, when this model is added as a relational node in the flexible editor, no text is appearing. On inspecting the interface div, I've found that it is a block element and is rendering outside of the bounds of the container div - setting the interface div to "display: inline" is resolving the issue - for now I've added CSS to my project settings.

https://github.com/formfcw/directus-extension-flexible-editor/assets/34007858/9d06db07-1046-4884-a114-7c2d35f47bc2

In the video I used a specific css selector for this example, but in my project I've added a less specific selector and have not come across any issues yet
`[interface="flexible-editor-interface"] { display: inline }`

**To Reproduce**
1. Add a flexible editor to a model.
2. Set up a relational node that contains a flexible editor field.
4. Set the display template of the flexible editor field to "flexible editor".
5. Set the display template of the model to your flexible editor field.
3. Add the relational node to the flexible editor from step 1.
6. Create/edit an item in the model from step 1. Insert the relational node making sure to populate the flexible editor field.
7. Your relational node will show the name of the name of the node with no value.

**Flexible Editor Version:**
1.1.0

**Directus Version:**
10.1.1

**Comment by formfcw** [comment]
Fixed with v1.1.5
