### ISSUE TITLE
Related nodes don't work when nested 2 groups deep

### ISSUE THREAD

**Issue by jdjoshuadavison** [formfcw/directus-extension-flexible-editor#26]
**Describe the bug**
Flexible editors only work up to 1 group deep. When you put a flexible editor field in a group within a group and add a relation node, it immediately gives the error that "the related item does not exist". The item is not created in the junction collection and the M2A reference field doesn't change.

**To Reproduce**
Steps to reproduce the behavior.

1. Add 2 group fields to your collection and put one inside the other
2. Add a flexible editor field to your collection, and put it inside both groups
![Screenshot 2023-09-29 at 09 52 09](https://github.com/formfcw/directus-extension-flexible-editor/assets/34007858/a5d147aa-767b-4a21-a304-920036411351)

3. Set up at least one relation node for the flexible editor
4. Create a new item in the collection
5. Add a related item to the flexible editor field
Immediately upon creating the related item, you'll see 'the related item does not exist'

**Flexible Editor and Directus Versions:**
- 1.1.0 in 10.4.3 ❌ 
- 1.1.5 in 10.6.1 ❌ 
- 1.1.5 in 10.7.0-beta.0 ❌

**Comment by formfcw** [comment]
Does the bug still occur on your system? I can't reproduce it.

![groups](https://github.com/formfcw/directus-extension-flexible-editor/assets/78852214/a234ef56-a866-42bb-b42a-7e138dc0b522)

The bug does not occur on my instance.
Can you give me some more information?

**Comment by madc** [comment]
We use this all the time and never had any issues:
![image](https://github.com/user-attachments/assets/bcc92133-6dd1-452a-8ce2-fe06af8187f9)

**Comment by sal1n** [comment]
Hi.  

I can replicate this issue in a clean v11 install:  https://github.com/sal1n/flexible-editor-issue  

Try adding an Image in the above example, credentials in the dockerfile.

If the editor is in a group under a group then I get the "the related item does not exist" message.  If I take the editor out of the group then it works as expected.
