### ISSUE TITLE
New collection being created when choosing an existing one for a junction

### ISSUE THREAD

**Issue by luigigorlero** [formfcw/directus-extension-flexible-editor#36]
**This is a Directus Bug, reporting here since it also affects this extension**
Selecting an existing junction collection creates a new collection, rendering Relational Content unusable https://github.com/directus/directus/issues/21628
![Screenshot 2024-03-01 alle 12 39 11](https://github.com/formfcw/directus-extension-flexible-editor/assets/22613842/88f79ae0-c828-43c2-8fca-5f6d2b2cde06)

**Directus Version:**
v10.9.3

**Comment by formfcw** [comment]
I will close this issue as this is Directus specific and does not affect Flexible Editor.
