### ISSUE TITLE
When creating a new block of the same type, it overwrites the latest block

### ISSUE THREAD

**Issue by JohannesPertl** [formfcw/directus-extension-flexible-editor#41]
**Describe the bug**
Creating a new block of type X will overwrite the last block in the editor, if this block is also of type X. 
This only occurs if directly adding a new block, without first clicking inside the text editing area.

Video:

https://github.com/formfcw/directus-extension-flexible-editor/assets/45853628/3b911e6c-7ce5-4e6e-ba71-d978b8fbf564

**Flexible Editor Version:**
[e.g. 1.4.0]

**Directus Version:**
[e.g. 10.10.5]

**Comment by formfcw** [comment]
Fixed with https://github.com/formfcw/directus-extension-flexible-editor/releases/tag/v1.4.1
