### ISSUE TITLE
Text Align is disabled if Code Block is not activated.

### ISSUE THREAD

**Issue by madc** [formfcw/directus-extension-flexible-editor#50]
**Describe the bug**
![image](https://github.com/user-attachments/assets/6c1566bb-bfb6-4a51-aa4c-2278bded2f1d)

**To Reproduce**
- Create a new field set as Flexible Editor
- Disable "Code Block" in tools
- Enable "Text Align" in tools

**Flexible Editor Version:**
1.7.0

**Directus Version:**
10.x - 11.x

**Comment by formfcw** [comment]
Thanks for reporting.

**Comment by madc** [comment]
https://github.com/formfcw/directus-extension-flexible-editor/blob/main/src/interface/tools/text-align/index.ts#L14

Is `codeBlock` need here?

**Comment by formfcw** [comment]
Does it fix the bug, if we remove the `"codeBlock"`?

**Comment by madc** [comment]
Looking [at the documentation](https://tiptap.dev/docs/editor/extensions/functionality/textalign#types), I think it doesn't make sense to have it here.
And I'd guess, removing it would fix the bug, but I don't have an easy way to test it atm.

**Comment by formfcw** [comment]
Will be fixed with the release of `v1.8.2` :rocket:
