### ISSUE TITLE
Sub-/Superscript not available

### ISSUE THREAD

**Issue by madc** [formfcw/directus-extension-flexible-editor#51]
**Describe the bug**
![image](https://github.com/user-attachments/assets/48910f38-a6a9-4016-a9a9-59c758587a6b)

Looking [at the code](https://github.com/formfcw/directus-extension-flexible-editor/blob/bc65cfff9754b3131abebe10e2929d7e38062dbb/src/interface/tools/index.ts#L40-L41), it should appear between Code and Link.

**To Reproduce**
-

**Flexible Editor Version:**
1.7.0

**Directus Version:**
10.x-11-x

**Comment by formfcw** [comment]
Thank you for reporting this. I can’t reproduce it, can you check again?

**Comment by madc** [comment]
Maybe I'm missing something, but I would expect to activate it using the tools menu:

![image](https://github.com/user-attachments/assets/1f542d82-05ed-4fa3-9de9-7a73dead8af7)
![image](https://github.com/user-attachments/assets/70f65d4c-f639-4e73-bf97-a4489e4cd0c6)
![image](https://github.com/user-attachments/assets/5f1c3efe-b3e6-43e2-93dd-fce229dd8d5c)
![image](https://github.com/user-attachments/assets/b9e454e4-6682-401b-97f7-3b5d185f4dd3)

Here the resulting editor:
![image](https://github.com/user-attachments/assets/05309858-dd3a-47cb-83e6-3138b1b92cb5)

Is there anything I can try?

**Comment by madc** [comment]
Sorry, my bad. Extension was still on 1.5.0. Updated and everything is OK.
Thank you for taking the time to respond!
