### ISSUE TITLE
After selecting a valid M2A field, no new fields appear

### ISSUE THREAD

**Issue by Krislunde** [formfcw/directus-extension-flexible-editor#56]
**Describe the bug**
I've followed the instructions in the repo. I've created the required junction collection, created a M2A field where I want the flexible editor, and selected the related collections I want to use with it. However, after selecting the valid editor_nodes M2A field, in the editor, the three new fields that are supposed to appear do not appear. So I can insert Blocks into the editor, but I can't choose what kind of Relation Inline Blocks I want for example.

**To Reproduce**
Follow instructions to create a Flexible Editor field on a collection.

**Flexible Editor Version:**
1.7.2

**Directus Version:**
11.1.0

<img width="863" alt="image" src="https://github.com/user-attachments/assets/3b9c950a-cbfe-4667-83a1-da78981e0760">

**Comment by formfcw** [comment]
Please upgrade to the latest version. Inline blocks and marks have only been available since 1.8.0.

**Comment by Krislunde** [comment]
Thanks for the reply. This was installed via the marketplace, so it's strange that an older version was installed. 

There doesn't seem to be any way to update extensions via the marketplace at the moment, will uninstalling and reinstalling the extension via the marketplace break fields already added, or is the recommended way to install via npm?

**Comment by formfcw** [comment]
Note, that the marketplace is in beta. Yes, via npm.
