### ISSUE TITLE
Issue with saving Inline Marks / Inline Blocks

### ISSUE THREAD

**Issue by JeromeTrottier** [formfcw/directus-extension-flexible-editor#57]
**Describe the bug**
When adding an inline block or inline mark in the Flexible Editor and saving the document using CMD+S (on Mac) or potentially CTRL+S (on other operating systems), custom marks and inline blocks are flagged with a warning indicating that the related item does not exist. This issue requires the user to recreate the inline mark or inline block. However, if the document is saved using the save button provided by Directus, the warning does not appear.

**To Reproduce**
- Add an inline mark or inline block.
- Save the document using CMD+S (on Mac) or CTRL+S (on other operating systems).
- Observe the warning indicating that the related item does not exist.

**Expected Behaviour**
When saving the document using CMD+S or CTRL+S, the custom marks and inline blocks should be saved correctly without any warnings.

**Actual Behaviour**
Saving the document using CMD+S or CTRL+S results in a warning that the related item does not exist, necessitating the recreation of the inline mark or inline block. This issue does not occur when using the save button provided by Directus.

**Flexible Editor Version:**
1.8.1

**Directus Version:**
11.1.0

**Comment by formfcw** [comment]
Thank you for reporting this issue. I can't reproduce this bug. Can you provide more details about your project/instance? What db version are you using? What collection do you have?

Can you reproduce the bug yourself?

**Comment by JeromeTrottier** [comment]
We can close this one, it was related to another extension
